language: python
python:
  - "pypy3"
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

cache: pip

env:
  global:
    - TOXENV=base,optional

install:
  - pip install tox

script:
  - tox

after_script:
  - python debug-info.py
