language: python
python:
  - "pypy3"
  - "pypy"
  - "3.6"
  - "3.5"
  - "2.7"

cache: pip

env:
  global:
    - PYTEST_COMMAND="coverage run -m pytest"
  matrix:
    - TOXENV=optional
    - TOXENV=base
    - TOXENV=six19-optional

matrix:
  include:
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7
      TOXENV=optional
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7
      TOXENV=base
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7
      TOXENV=six19-optional

install:
  - pip install tox codecov

script:
  - tox

after_script:
  - python debug-info.py

after_success:
  - codecov
