language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - USE_OPTIONAL=true
  - USE_OPTIONAL=false
  - DEP_VERSION=min USE_OPTIONAL=true

install:
  - ./requirements-install.sh

script:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then py.test; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m pytest; fi
  - bash flake8-run.sh

after_script:
  - python debug-info.py

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage combine && codecov; fi
