language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

env:
  - USE_OPTIONAL=true
  - USE_OPTIONAL=false

matrix:
  exclude:
    - python: "2.7"
      env: USE_OPTIONAL=false
  include:
    - python: "2.7"
      env: USE_OPTIONAL=false FLAKE=true

before_install:
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt -r requirements-test.txt --use-mirrors
  - if [[ $USE_OPTIONAL == "true" ]]; then pip install -r requirements-optional.txt --use-mirrors; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 3.* && $USE_OPTIONAL == "true" ]]; then pip install -r requirements-optional-2.txt --use-mirrors; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.* && $USE_OPTIONAL == "true" ]]; then pip install -r requirements-optional-3.txt --use-mirrors; fi
  - if [[ $TRAVIS_PYTHON_VERSION != "pypy" && $USE_OPTIONAL == "true" ]]; then pip install -r requirements-optional-cpython.txt --use-mirrors; fi
  - if [[ $FLAKE == "true" ]]; then pip install --use-mirrors flake8; fi

script:
  - nosetests
  - if [[ $FLAKE == "true" ]]; then flake8 --exclude=E,W html5lib; fi

after_script:
  - python debug-info.py
